using UnityEngine;

public class ShellExplosion : MonoBehaviour
{
    public LayerMask m_TankMask;
    public ParticleSystem m_ExplosionParticles;       
    public AudioSource m_ExplosionAudio;              
    public float m_MaxDamage = 100f;                  
    public float m_ExplosionForce = 1000f;            
    public float m_MaxLifeTime = 2f;                  
    public float m_ExplosionRadius = 5f;              


    private void Start()
    {
        Destroy(gameObject, m_MaxLifeTime);
    }

	private void ExplosionPushTarget(Collider target) {
		Rigidbody targetRigitBody = target.GetComponent<Rigidbody> ();
		
		if (targetRigitBody) {
			targetRigitBody.AddExplosionForce (
				m_ExplosionForce, 
				transform.position, 
				m_ExplosionRadius);
		}
	}
	
	private void ExplosionDamageTarget(Collider target) {
		Rigidbody targetRigitBody = target.GetComponent<Rigidbody> ();
		TankHealth targetHealth = target.GetComponent<TankHealth> ();
		
		if (targetRigitBody && targetHealth) {
			float damage =CalculateDamage(targetRigitBody.position);
			targetHealth.TakeDamage(damage);
		}
	}

	private void Explode() {
		m_ExplosionParticles.transform.parent = null;

		m_ExplosionParticles.Play ();
		m_ExplosionAudio.Play ();

		Destroy (m_ExplosionParticles.gameObject, m_ExplosionParticles.duration);
		Destroy (gameObject);
	}

    private void OnTriggerEnter(Collider other)
    {
		Collider[] colliders = Physics.OverlapSphere (
			transform.position, 
			m_ExplosionRadius,
			m_TankMask);

		for (int i = 0; i < colliders.Length; i++) {
			ExplosionPushTarget(colliders[i]);
			ExplosionDamageTarget(colliders[i]);
		}

		Explode ();
    }


    private float CalculateDamage(Vector3 targetPosition)
    {
		Vector3 explosionToTarget = targetPosition - transform.position;
		float explosionDistance = explosionToTarget.magnitude;
		float relativeDistance = (m_ExplosionRadius - explosionDistance) / m_ExplosionRadius;

		float damage = relativeDistance * m_MaxDamage;
		damage = Mathf.Max (0f, damage);

		return damage;
    }
}